In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [2]:
race_results = pd.read_csv('./Data/2022_Race_Results.csv')
race_results.head()

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,+1 Pt,Fastest Lap
0,Bahrain,1,16,Charles Leclerc,Ferrari,1.0,57,1:37:33.584,26,Yes,1:34.570
1,Bahrain,2,55,Carlos Sainz,Ferrari,3.0,57,+5.598,18,No,1:35.740
2,Bahrain,3,44,Lewis Hamilton,Mercedes,5.0,57,+9.675,15,No,1:36.228
3,Bahrain,4,63,George Russell,Mercedes,9.0,57,+11.211,12,No,1:36.302
4,Bahrain,5,20,Kevin Magnussen,Haas Ferrari,7.0,57,+14.754,10,No,1:36.623

In [3]:
quali_results = pd.read_csv('./Data/2022_Qualifying_Results.csv')
quali_results.head()

,Track,Position,No,Driver,Team,Q1,Q2,Q3,Laps
0,Bahrain,1,16,Charles Leclerc,Ferrari,1:31.471,1:30.932,1:30.558,15
1,Bahrain,2,1,Max Verstappen,Red Bull Racing RBPT,1:31.785,1:30.757,1:30.681,14
2,Bahrain,3,55,Carlos Sainz,Ferrari,1:31.567,1:30.787,1:30.687,15
3,Bahrain,4,11,Sergio Perez,Red Bull Racing RBPT,1:32.311,1:31.008,1:30.921,18
4,Bahrain,5,44,Lewis Hamilton,Mercedes,1:32.285,1:31.048,1:31.238,17

In [4]:
sprint_results = pd.read_csv('./Data/2022_Sprint_Results.csv')
sprint_results.head()

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points
0,Emilia Romagna,1,1,Max Verstappen,Red Bull Racing RBPT,1,21,30:39.567,8
1,Emilia Romagna,2,16,Charles Leclerc,Ferrari,2,21,+2.975,7
2,Emilia Romagna,3,11,Sergio Perez,Red Bull Racing RBPT,7,21,+4.721,6
3,Emilia Romagna,4,55,Carlos Sainz,Ferrari,10,21,+17.578,5
4,Emilia Romagna,5,4,Lando Norris,McLaren Mercedes,3,21,+24.561,4